### ISSUE TITLE
DOWNLOAD

### ISSUE THREAD

**Issue by JMatras** [midhunhk/message-counter#67]
Hi all,

I would like to download this app, but I can´t find where. I think the link is broken, because if I click on the "alternate source" then I moved to Wiki or now after singing up to creating of a new page. 

Can someone help, please?

**Comment by midhunhk** [comment]
Thanks for pointing out the missing link. I have recreated the page with the table of alternate sources.

https://github.com/midhunhk/message-counter/wiki/Alternate-Sources

The latest APK is always available from the Github Releases page - https://github.com/midhunhk/message-counter/releases
