### ISSUE TITLE
Contador de mensajes 

### ISSUE THREAD

**Issue by Calena13** [midhunhk/message-counter#71]
**Describe the bug**

**To Reproduce**
3. Perform an action '....'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S8]
 - OS: [e.g. Android 8.0]
 - Application Version [e.g. 3.0.0]

**Additional context**

**Comment by Calena13** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Perform an action '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Samsung Galaxy S8]
> * OS: [e.g. Android 8.0]
> * Application Version [e.g. 3.0.0]
> 
> **Additional context** Add any other context about the problem here.

https://github.com/midhunhk/message-counter/issues/71#issue-1717991674

**Comment by midhunhk** [comment]
No clear details mentioned in this ticket.
